# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: NDZiMjA1YmI2ODBiMmY1MjY0ZWQ1ZDU5MzA2OTZiNTZmMWI5NTc2ODEyYTU1MzI4OTk1NDUyZDM5ZjhlZDRjYjI3ZjU2YTZhYWRjZGY5ZTJjZWViNjAxMWNkY2Y0YjE3OTI5MmM5ZjgwNjkwM2JmYTRkYzI0MzQ2YjQ3YTViNzk=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
